server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&serverTimezone=UTC
    password: admin
    username: root
mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml